sudo: required
services:
  - docker


before_install:
  - docker build -t arunreddy2786/fibonacci-test -f ./client/Dockerfile.dev ./client


script:
  - docker run arunreddy2786/fibonacci-test npm test -- --coverage

after_success:
  - docker build -t arunreddy2786/fibonacci-multi-client ./client
  - docker build -t arunreddy2786/fibonacci-multi-nginx ./nginx
  - docker build -t arunreddy2786/fibonacci-multi-worker ./worker
  - docker build -t arunreddy2786/fibonacci-multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arunreddy2786/fibonacci-multi-client
  - docker push arunreddy2786/fibonacci-multi-nginx
  - docker push arunreddy2786/fibonacci-multi-worker
  - docker push arunreddy2786/fibonacci-multi-server


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "fibonacci-multi-docker"
  env: "FibonacciMultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-154242726126"
  bucket_path: "fibonacci-multi-docker"
  on:
    branch: master #Only the code from master branch gets deployed
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
